/**
 * arceane-header.js
 * Header partagé Arcéane Tools — auto-sync avec index.html
 *
 * Usage dans n'importe quel outil :
 *   <script src="arceane-header.js"></script>
 *
 * Le header se génère automatiquement et liste les outils
 * référencés dans index.html (même répertoire).
 */

(function () {
  // ── Config ────────────────────────────────────────────────────────
  const INDEX_URL = 'https://arceane-tools.vercel.app/';
const MENU_URL  = 'https://arceane-tools.vercel.app/';
  const LOGO_B64    = 'iVBORw0KGgoAAAANSUhEUgAABtUAAAQnCAYAAACE4OPBAABccUlEQVR42uzdb8xd1X0n+i9RNL1ziUmVlLntZHp5ojQBRbcVE0ycBDGKsDEqSJWNKg2uzFRMGim2IqFKIQ4gXiEgJEgjpMiO1GaiXqzaI0VgRSIjjEFVEUkphkEzV5VJGvF4Mml7hyZqcX1npm+4L/Y5+LF57PX8OXvtf5+PFAEOnLXPb6+zzz7ru9dal7399tsBAAAAAAAALu49SgAAAAAAAACXJlQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQ8F4lADq0bfbXf77izz6y4u8/mOTKTbz+6ST/Y/b3P0vyd7O//6vZX19yCgAAAAAAWIvL3n77bVUA2rQtyfuSXJEmMPunSa7q2TGeThO6/XWSv03ygtMGAAAAAMBKQjVgkW5M8ktpwrNfTXL5wN/PqSQ/TfLfkzzn9AIAAAAATJdQDdiobWmWbfyVJFdn+AHaWpxN8nqS5STf0wUAAAAAAKZDqAas1TxE+0iSa5QjSfJmkh8m+a8xkw0AAAAAYNSEasClbE8zC20qM9E269WYxQYAAAAAMEpCNeBCu5P8X0muUopNOZ3k+zGDDQAAAABgFIRqQJLsSfIbSa5Uila8muS/JHlBKQAAAAAAhkmoBtO1O8knI0ir6WySP0nylFIAAAAAAAyLUA2mZXuSz8TSjn3wYpJvKwMAAAAAwDAI1WD8tiX5eJJrk1yuHL1zKs2ykC8pBQAAE/FGkqWO2l5O8mGnAACAjRCqwXhtT7IjlnccCuEaAABTsDfJEx22f5lTAADAhm8mhWowOnuSfCpmpQ2VcA0AgDHrcpbaV5I86hQAALBRQjUYh21JrkvyCaUYjVNJHlMGAABGpMtZaseT3OIUAACwGUI1GLZtSW5Mco1SjNZzSY4oAwAAI9DVLLUzSa5QfgAANuu9SgCDtD3Jv4wwbSrn+lNJvpsmYAMAgCHal+6Wfbxd+QEAWAQz1WBYtiXZleRKpZgkS0ICADBUbyXZ0kG7jyS5T/kBAFgEoRoMg2UemTub5Jkk31MKAAAG4kCSr3bQ7skk1ys/AACLIlSDfhOmcTFmrQEAMBRdzFKzjxoAAAtnTzXor7uS3KAMXMQ1SR5P8p0kLygHsEnPtPjaX09yQokBJutAuln28d8oPQAAiyZUg/7ZneQ2ZWANLk/yu0n+RZIjygFs0MEkO1t8/Z9HqAYwZfd30OYjSY4pPQAAi2b5R+iP7Ul+K01QAut1OsmDygBsQI2bwcuUGWCSuthLzT5qAAC0RqgG/fCl2DeNzTub5G5lANah1mDnoST7lRtgcmoPONhHDQCAVgnVoFuWemTRzsY+a8DavZV6+9yYrQYwLQeT7Kvc5p1JDis9AABtEapBN7Yl2ZXkSqWgJUeSPKcMwCXsTfJExfa+kuRRZQeYjNqDDUeT7FF2AADaJFSD+vak2T8N2vZikm8rA3ARbyRZqtieJbkApqP2LLXlJB9WdgAA2iZUg3puTPLbSS5XCioSrAGr2ZXkqQ7atSwXwDTUHmiwxDAAAFW8Rwmgij1JfjcCNeq7IcldygBcYF9H7T6o9ACjd7Bye/uVHACAWsxUg/Y9Enun0T0z1oC5HUme7bD93UmOOQ0AvmMW4HiSW5QdAIBazFSD9uxO8ocRqNEPN8TG7UDj9o7b3+cUAIzWPRXbOhOBGgAAlZmpBu34UpJrlIEeOpLkOWWASevDzd/NSU44FQCjUnuWmu8SAACqM1MNFmtbkscjUKO/9iTZrgwwWQd7chy3OxUAo1NzltpXIlADAKADZqrB4uxOcpsyMABnk9ytDDBJbyXZ0pf7UKcDYDRqzlI7meR6JQcAoAtmqsFi7I9AjeG4PM2MSmBaDqQ/gVrSn1lzAGxerVlqZyJQAwCgQ2aqweY9kOQqZWCATiV5TBlgMt5IstSj4zmT5AqnBWDwdiV5qlJbu5McU3IAALpiphps3I1pZvsI1Biqa9IMTADjtzf9CtSSZtbcAacGYPD+XaV2HolADQCAjpmpBhtza5LblYGR+KMkLygDjFrfZqnNLSf5sNMDMFh7kzxRoR37qAEA0AtmqsH63RWBGuPy20oAo7Yj/QzUMjuuvU4RwGA9WKEN+6gBANAbQjVYny8luUEZGJnLk+xXBhite3p+fA86RQCDVGtpYfepAAD0huUfYe0eiP3TGDfLQMI4DeFm7+YkJ5wqgEGpsbTw0SR7lBoAgL4wUw3W5pEI1Bi/W5UARufgQI7zHqcKYFBqzFJbjkANAICeMVMNyh5PszweTMFzSY4oA4zGkG70LnO6AAbjrSRbfC8AADA1ZqrBpQnUmJrtSgCj8fDAjvegUwYwCAfSfqBmHzUAAHrJTDW4OIHatJ1O8j+S/H9J/nr2Z/8ryc82+HofTPILs7//xdk/J8k1PXzvLyb5ti4Ag1djFsHC702dNoDJf7/YRw0AgN56rxLAqgRq03AqTUj2d0n+Nsk/Jnmpo2PZluSfJPmlJB9JE7pd2dGx3JDkLzqsBbB5+zK8QC1pZj886vQB9Po63eb3y5kI1AAA6DEz1eDdBGrj82aSn6SZcfZXGVZYtC3JP0/yK0murtg3TyV5TNeBwXojydIAj/tMkiucPoDeanuW2s1JTigzAAB9ZaYanE+gNnxn0wRoP87wArTVrHb8tyb5eNpdOvKaNIGe2WowPHszzEAtaQZq9yU55DQC9E7bs9S+EoEaAAA9Z6YanCNQG6azSV5PspzkexN8/zcm+bUk17bQf+2tBsP0cpKtAz7+5SQfdhoBeqfNWWrHk9yixAAA9J1QDRoCtWE5lWYm2lNKcZ55wHbDAl/z95QVBmVHkmdH8D7uTHLY6QTojYNpZhK3wdK/AAAMhlANBGpDcDbJa0n+a5LnlGNNtif5TJKrNvk6T0d4CUPyTJKdI3gfJ5Nc73QC9MaBFl/7lVj2EQCAgRCqMXUCtf56M8l/TvLfkrygHJtyVzY+e+1skruVEAZjTDd2N8cgKwAAANAjQjWm7IFsfhYPizWfkWYfr3bsTvLZrD9I/qMINmEI2lyaa6WTqbNn29Eke5xWAAAAoC+EakyVQK1fXkzylxHc1LLecO3FCDphCGrc1M33vXkryZYa96pOKwAAANAX71ECJuiuCNT64FSSI0l+L01gI1Cr56k0Szo+nWZ2YMm1Sga9d6BSO4dnf32oUnsHnVoAAACgL8xUY2p2J7lNGTpzNsmfpQnT6I89SbYX/h1LQEK/dTFzrNZNpNlqAAAAQC+YqcaUbI9ArSun0wRpd0eg1kfzGYOvXuLf+TVlgt7amzqB2vEL/vlQpfd3wCkGAAAA+sBMNabk8ax9DykWw15cw7Mtya4kV17w528muVd5oJfeSLJUoZ2bk5y44M9q7uMGAAAA0Ckz1ZiKRyJQq+Vsmr265nulMSwvpQnPnr7gz69UGuilvakTqC3n3YFa8u7Za23YMnufAAAAAJ0SqjEFX4pAoIY3c26Jx6eUY/CeShOMnl7xZzcqC/TOnZXaeeAif15rCcgHnWoAAACga5Z/ZOz2pNlLjfa8mWb2wnNKMVq70+xH+HQEptAnO5I8W6Gd0vKLtZaf3J3kmNMOAAAAdMVMNcbsxgjU2jSfmXZvBGpjN5+19otKAb3yuUrtPFT4/x+odBz7nHIAAACgS2aqMWaPxz5qbTAzDaAfat3EXbaGf+etNHufte3mrL63GwAAAEDrzFRjrB6IQG3RzEwD6I+DldpZ655p36h0PLc79QAAAEBXzFRjjOyjtlhnk3w3gjSAPqk1M+yydfy7fZo5BwAAALBwZqoxNtsiUFuUs0meTnJ3BGoAfXIgdQK14+v89w9Vev8HdQEAAACgC2aqMTaPJLlSGTbtxSTfVgaAXqo1S213kmPr+Pd3JHm2wnGdSXKFbgAAAADUZqYaY7InArXNOpXk9yJQA+irvakTqC1nfYFakpxIcrLCsW1JM1sPAAAAoCqhGmNxYyz7uBlvJvmjJI8pBUCvPVipna9t8L97vNLxfUFXAAAAAGqz/CNj8XiSy5VhQ55O8pQyAPTerkrX680ur/hGkqUKx3lnksO6BQAAAFCLmWqMwZ4I1DZivtSjQA1gGPZVaucbm/zvv1npOB/UJQAAAICazFRj6LYl+bwyrMvZJN9N8pxSAAxKrZu2yxbwGm+lzt5vN6fZyw2oZ0eSj6aZ0fr+JNet+P8+lkvPVD2T5AcX/NkrSf5+9vevJ/kHn+tB942VnEcAAEbnvUrAwO1UgnV5NclBZQAYnFrX7kMLep3DqTOz7p4YtOV8Fw7q/3KSD13k370wEFrpFqXMriRXJ7kp5bBsrbascv9+qfv5eQj34ySnk/w0yd/43HfyuZoHqTfN/uzTWf/DEytD1XmY+orzObk+dLFr7weSbJ39/XKSH67j9X+e5LVV/vyVC/5ZX3NvcKl7g2tn/XCznr+g/+l30+hj8+vaTatc09bi+AXXs7eS/Ej/gX4yU40h253kNmVYk7NJvpPkBaUAGKRaN2yLnPk1pJl19NN8EGzl4NdVST4y+/v1DlboV5e2L8m/mt1fbxnA8S6nGXR/Ps0Mt2M+MguxK+fC1E9X7AvzwO35CNqGft2+Lk048anU2WN1o06mGbxOzoUg80Hs6IODuje4MKjt48PXrnHjsTfJx2d9bmcH/cc9D/SAUI0hezz2UlsLs9MAhu3hJPdWaOdkkusX+HrPVPqheSjJft1kUOYDYqvNWqg5iH/J30kTOA+7Zp/R30y/B77X40ySp9M84W3Qcn3fMzenvZB6M99L/z6Lm0VNO9eRT/a0/yyyH/4852ZXWqa2vXuD96UJ9ZNzs8Y+MPK+9WyS+5x+90sb7D/fSfKoUwQd/FgUqjFQdyW5QRkuyew0gHGotT/ZnWmWbVyUHbOBgir3tLpJr8xDswuXwRnSst1j7VO7Zudhb4YxG20R5oNOQrbzHcywAtXlJEdi8LkP9qaZ0XqHUiRplmybL9dmidpL3xvMH6a5Nk1Y1pcHafrgzOw+/En9x3VuE9+Rfx6z2KDOj0WhGgO0LcnnleGSzE4DGIcDSb5a6YfYh1t43TdSZ8D2K/GUZm07cm7ppWszvsGxsYVqDyfZk/HMSNuMo0n+NNOc/XQgyRdG0A9Oplm15LDuXPWaf3umFcgvwvGc2xNyCku2zZf/nM9AX9R+nFPjGuc6t9nfdV+LWd7Q7o9FoRoD9ECa/TR4t7NJvpvkOaUAGIWhh1J7kzxR4fjPpHnymcWbD5DN9zKbylPll43k3N2eZq80VjeV5QUPjrQfnEnyjZi91qa9SR6MYKSNa8/P0+yPNMTZbRfeG+x0Slu7xj0UD47VuM7dnXEuM2qZfGjrx6JQjYHZnuYpW97t9OwHDwDj+YE3hkCq1vKV++OJzM0wQHbB76SBn8t7nMPJnO9L9YPPZTpL9Bk4XKyxzGockuNJbhnAcRpErO/M7DPpPnfxv7Wm8tDAUK4vMJwfD0I1BuaRJFcqw7s8neQpZQAYlZdT54nJtgcih76E5dj5MXCR30kDPGZh2saMcaDpSKa535VZHZu3N83MRks8uha5b+if5SS/H3tmLeI6N9UZuB5AgQV5jxIwILsjULvQ2SR/EIEawNjsSL0lSNr+YVVrcHNp9iOZ9fUzxuFgkmcjUNuIV0b0Xh5OM+B9x0TP5ZY0D3G8FcuebsQzaWbIC9Sgn5bSjP08rBQbvu99eXadW5poDfbN7hP0IdgkoRpD8lklOM+pNOs+v6QUAKNzT6V2jldqp9ZyNXfqOkzMgQgQNusnI3gPu2b94F6nM0kTCh1MM2OPsnkYK5SHYbg3zb7LHo5au/nDR1uVQh+CRRCqMRS7k1yuDO94OsljygAwWrUGtr5eqZ39FevmxyFT8XKaWTlmlWzOjwZ+/EfSzFzQD97tjjRh4y6luKg3IoyFIVpKExJ5qObSdsTDR6U+ZNYabIBQjaH4rBIkaZZ7/KNY7hFgzA5Wamc5yYmK76vWrLjP6UKM3IE0s0o8bb0YJwZ87G9kuks9rtWW2W+ng0pxnvkSYEtKAYP/3eD6dvH7pWfjoZOS+aw1YB2EagyBWWqN02mWe3xBKQBGrdaTlA9Ufl9PVGrHADNj9kya2WksxsmBHvc8WF1yCtf13fqyMiRpZjcahIdxXd+eUYbzvOx+aV2WYmY3rItQjSH4rBLkxSQPKgPA6B2o1M6ZJIcrv7fDaWbH1WCwkDF6K/Y8WrQhhiyC1Y3bOvscTZnZjTBOO+PBgeTcHqNm86/ffGa3pTJhDYRq9N2tMUvtySTf1hUAJuH+Su081NH7+1qldvwYZEz2ppmVZPmixfsvAzvelyNY3awtaQZc907wvb8VsxthzLammYk65fsle4xuniVFYQ2EavTdjRN+7/P9076nGwBMwr6KPwIf7eg9HkozS66GA7oUI7kuPKEMrfnRgI71jXjyflG2zD5XUwrW3oqBZpiCOzLNQOSA+6WF338K1uAShGr02fYkV070vb8Z+6cBTM2XK7VzqOP3+Y1K7dyvSzFwnhRu34mBHKcZRu2YSrAmUINp2Zfk4YndL1kWuZ1+5D4ULkKoRp99ZqLv+3SSe51+gEnZm3oDpvs7fq/3VWpnS6a5vBfjcDCWMW3b8kCOUyDSrieS7Bjx+9N/YJruHfm1zf1SHYI1uIj3KgE9tS3JVRN83y/G/mkAU3RnpXaO9+T9Hk2zPE3bHkxyWPdiYAwQ1fFnAzjGIQUiy0l+uMqff3oA7+HJJFeMsI8L1GDaxnptG/r90skkv5ThzECf13i/jxScI1Sjrz4+wfcsUAOYph1JdlZq61BP3vO3UidUW0qyK8kx3YyBGOoA0Tywf37Fn72e5B8u8u//cpIPrfjnm2Z/rRnAvNbzmvYxEFlOE0a+luSVrH/5zB1J3pfk6tk539mT97VlVu8xDT6/HIEaTN2WJM8kuWWE721fT++XlpP8xzQrUL0y+7O1flfuWHF/dFP69VDKviTfj4cV4R2Xvf3226pAH/3hxN7vkSTPOe0Ak3QkdQKm5SQf7tH7fjnJ1grtHB/pYMIi7EjyrDKs/jupgzb3plmKrs/OJPlBmvDs9bQbWO9I8tE0QcdNST6WxT7VfXP6u6darevjWhxN8nTaHUh7OMmedP/U/li+L55JfwLLS9U6s2vJW0l+tOL/O7GGa8NqLgzr35/kuhX/PISaDKH/GUQcnjszrjCkT/dLZ2a1Pd7iPdG+JP+2B/cFZzLumY+wvh+LQjV6aHeS2yb0fgVqANNW62Zsf/ozU632D+I+D553Sah2id9JldvbleSpntZieXa/el+P+u0inuS+rKf17kOgdjLJ4+lmEPbhJF9Md0/nP9Kjvr7R+vVtf+4zaYLZ17KxGY5tXUeSc8H9VUk+ksWH9+shVOvuevfzDfx3XfaVjXwGxxKG9OV+6VDaDdIuZl+SL3fY95bTr4c0obsfi0I1euiRJFdO4H2eTfLdCNQApqzWUm99/TH9RqUfhYdiH4DVCNUu8Tupcnt9W+pvOck3kzw6oHO2K+eWFSwFbX29Jna9/OehNHvw9CH06HLgcHeGuWzwrvQrnO9q0HmR35HzAP/aJB9Iu7PdhGqbszIcW7kU8Ssr/v5Ei5+9T6Z5iGtrT+sz9AcG+nC/dCbJN3pSx12z78kuZuBaBQQiVKN/bkzyuxN4n2eT3O10A0xerRuxvv6QPpDkq7Xue3W3d5laqLaep9FrDhb0aam/42lmkI5lmahdaQY6r8v5A099HBDqcjmr40m+nn7O6D2Q5P7UHUQd6qyOPoTzy0keyHj33Xm75c+hUO3i/eqHSX6cZq+qlUuG9vG6tTfN6kt39Oy4hn4v3OX9Ul9/S+1K8u9S/wGUsS0pCuu/oArV6Jm7ktww8vcoUAMgESjNTT1Y7FKfQrXjK/7+52mWCVvplYv8d0Nf1rPrmUkr6//1jH+Z1Pk+bT/q4XvtIhA5k2YW7xAGxmrtPzrU74za9bnQcsYdptW4ZxGqnZsl/VZPr9ND/p5Phr1yQ1dL2w7lc7lv1tdq3j/YX41JE6rRN3848vcnUANgrtYAat9/QE99CcwutR2qzWeGzZ8sT86FY/a468dSbctJfj/DXZ5tLLp4+v5okj0Dq9O+NEuS1gofh7IfZ5fXkjNpHhI6NJHPqlCt3Rp8JcNadriP97slQ5yt1tVDYH3bj7pv9xOW12fS3qME9Mj2kb8/gRoAc3tTb1DwyZ7XotaPsS1pBv6o5940A4T70wySPZpmgFqg1vi/e/DZ+3AEal07kPqB2v4ML1BLmgG8K9KEwTU84lpySUdn5+OQjzGs6bp7c5oHjrr+zhma2r9lTqYJH4d4bbu+4nHvSxN4wiQJ1eiTq0f83gRqAKz0YMUfhUMIMI5XaucLuh49cSTd7X005MGiMfpqxbbOJNk9gnP/4dQZmN6a5iGYPjvQ0bXkzgwzmIUunUjd0GM19w+sZg9XvsadnJ2jIdufeg+F/IGPNVMlVKNPPjHS9yVQA2ClXam3mfTjA6lJrcGFpfR/gJTx25Hu9j56JMMfLBqTZyq2NV8C99hIand96gRrD/a8Dl+t3N6ZNKH8YR9f2LD9aYLpLmwZ0L3wjtTdR+3QiO6R7qvUx/y2YrKEavTFWJd+FKgBcKFa+yksZziDXsdSbzmvB3VBOtbVknJ3phlkoR92JdlZqa2x7ilZI1hbSn8HDA9Wbu9k7E0Ki3J49r18poO2bxtIje6p2NYY9web97G2GfNkkoRq9MUYl34UqAFwoR2pN4j6zYHV5oFK7SzF+v90Z2/q7591Js0+LmaW9Mu/q3j+xxyE1AjW+vowxr6KbY1hSTTom8MdXZ/vGEBt9lb8zTTGQG1lH2t7RZCtflsxRUI1+mJsSz8K1ABYze0V23p0gD/6aj2te4+uSEdqD87PA5UTSt8re1NvGeDbJ1DP61v+/lhK/2ar1ZylJlCDdnWxFGTfl+yruf/0/pH3r/1JjvptBYslVKMPxrj043ecVgBWUeup8kMDrc9DldrZqSvS0ed/qWJ7Y5+hNGS1Bgv3ZzqBatuDon17YLLW/cSZCNSgbYdTf2noPi8BWevBkyld3/ak3aX2/bZicoRq9MH/ObL3cyTJC04rABeo+VT5UJ+4fHSk5wNq92+BWn/VGiw8muE+YLERh9Puk/hbe/ReD1Rsy3UE6rgv7S9lu9KnelyLWg+e3D6xPvb5ll//YR9jpkSoRh9cO6L3ciTJc04pAKuotczK8YHXqdYg8D5dksqf/y0V29uv5L1VY7DwTJqn0qdmT9pdBrIv3xv3u47AKNWcNbXU4/ulGsf2lUxvaewTLf/O+qKPMFMiVKMPLh/J+3gxAjUAVncg9QbUvz7wWj1Z+bxADTX3Unskzawd+mdH6gwW/puJf9+25cs9eH+7Kt1PTG2mI/TFVypfT/qmxv5yyxne3tOLsj/tPXyypad9ClohVKNru0fyPl5M8m2nE4CL+EKldpYz/KcuT6TebLv7dU0qqBWkJM3SUfcpeW99rkIbR5Mcm3CND6W9fWOWevD+/nWFNqY60xH64NG0O+N2pU/28P3X2Jvr8xPvYwcGfv6gF4RqdO0jI3gPpyNQA+Diai1jkiQPjKRmT1RqZ0ssA0n7au3ZcSZ1l45i/e6o0IYwpN3vwocn0Ice0oWgU7U+g9f17H3X2O/4aKa37OOFDqW94NbvKiZDqEbXrhn48Z9N3eV8ABieWt8TZzKeJd8Op72ZBhf6si5Ky2oNMFjOVD+wXF/73yE3d/i+auzNupzpLosGfVFrttqne/a+a1zjPHjSaDO43aG8TIFQjS5tG/jxn01yt9MIQOFHxdIIfhx14WuV2lmq9COeaarVt05GoNJ3NQL8/cr8jm+29LpbO3xPt1Vo4wFdB3qhxoNyW3r0fndVOB73See0Gdxep7xMgVCNLv3zgR//d51CAAruqfzjaEzaXJrkQnfqqrTktkrt3KvUvbdU4ZpJne/EXR29p7aXflzOeGa8w9BN7SGJf62m1bV1vb9JaZkCoRpd+pUBH/tzs/8BwKXU2qx5rIOphyueJ0uV0IY7Kn3+Tyh1r9VYmvNJZX6Xoy297tUdvJddFdowSw36ZblCG325/237IaTjulO1muxUWqZAqEaXrh7ocZ9KcsTpA6DgYMW2xvrkZc339TldlgXb6/PPzG+3/PonI1hdzdMtvW4XT+G3PUg5pn1ZYSxqjDt9tAfvc1faX/rxCd3pXY6lvVVBPKzI6AnV6NLlAzzms0kec+oAWIN9ldoZ+5OXRyu1c4cuy4J9xuefmbb34fr3SryqtkKiLp7C/82WX/8bugv0zvMV2riiB+/TQwPj+578qNIydkI1unLjQI/7j506ANbgQMW2xv7k5bcqtnVQ12WBfrNCG19X5t6rMWPRfmoXtzyS97HU8uvfp6tA70xlBnLb90sCtYv7fkuv+6tKy9gJ1ejKLw3wmJ9O8pJTB8Aa3F+pneUJ/FA8kXqDovt0XRZoqcLn35J//df2jMWTSnxJ/7Gl1625tNWuCtcSoJ+mcI1v+37JrP6La+t35HVKy9gJ1ejKrwzseE8necppA2AN9qX9fQHmvjaRmj5Qsa0DujALUGN20jeVeRDafgLf0o+X1tZT+DUHDNvei9y1BPrrZfdLm3Imzd5hXNxyC6/5aWVl7IRqdGVIU4HPJnnQKQNgjb5cqZ0zmc6SX4fT3kbaF7pfF2YBPl6hjUeVeRCWWn59Sz9e2t+M4D3c1PLrv6KbQG+ddr+0KU/rQkU/bOE1tygrYydUoytXDuhYn3G6AFijvWl/AHXuGxOr7UOV2tmSOrOMGLe2Z7FY8m8Y2l4i8IwSF7W1ROpNFd/Dp1vuQ5aRhf4ae+jd9v3Sn+pCk+9j0AqhGlzaqSTfUwYA1ujuim3dN7Ha1pyVY4Y6m7Wz5df/jhIPQtuDhT9Q4jVZHvjxt/nEv1kcwJjvl36kxEU/ael1dygtYyZUows3DuQ4zyZ5zOkCYB0/HLZWauvoRGtca5mzpSS7dGl6zFPFw3BVy6//vBKvyQ8HfOxtD0q+pntAr5lJqn5tEzzCBgjV6MIvDeQ4LfsIwHrcU7Gtb020xvsrtrVPl2aDajyZa5BoGD7S8uu/rsSd2VmpnV9u+fUF9MBY75eOK3GnflkJGDOhGl34xQEco2UfAVivWgNsJzPtAfXjFc+nZUvYCPupUet74ZgSr8mQg6MPtfz6AnpgrPdLP1fiTr8HPqS0jJlQjS58cADHaNlHANbjYMW2Hp94rQ9VbOt2XZseelYJYF3+fsDH3uYSomd0DaBD72/59V9TYqAt71UCeBebNQOwXrWWClxOcnjitT42q8NSpfO6X/dmnW5q+fX/QokHocZMV8vVr83HBnzsbS4h+gNdA+hQ2zPVrk1yQJmBNgjV6MI1PT62N5M85RQBsA41f6x9U7mTJA8keaJSWw8nuU/J6ZG/UQJmdioBm2A/NWDM7pj9D2DhLP8I57OmPADrdX/Fth5V7iTNbL1ay1Z9UblZpw+4XyXtP4HPNLQZnP698gIjvb4BtEqoBuecTvKcMgCwDnuTbKnU1iHlPs83KrWzJZaOYX22KgEwAG8pAQDA+gnVqG1bj4/tuNMDwDo9WLEte3udr+aSjF9QbnripBIAC/IjJQAAWD+hGjROJXlJGQBYh71Jliq15cGP1dWavbc0O9/QtZ8rwWC8XwkAAGB8hGrQeEEJAFinOyu29XXlXtWTFdt6ULmBdbCnGpu1QwkA1zeA/hGqUdsHe3hMZqkBsJEfgrU2115OckLJV3Ui9ZbDWzIAAMCK72YAYHWvKAFj9l4loLJf6OExPea0ALBOt1ds64dJDij5RdVcDu+eCDgBaL6bh873GQDABgjVmLpTSgDABuyr2NbO1JsVR/lcAAAAABNl+Uemzl5qAKzXQSVw/gEAAIDpEaoxZfZSA2Aj9irBpO1TAoDJs1cMAFycJYYZNaEaU/aflACAdTqQZIsy6AdKADBpfz+C97DDaQQAWD+hGlN1NslzygDvcpcSwCXdrwToB8AaPK8Eo/ZWhTY85Q+MlevbuJ1RAsZOqMZU/YkSwLvsT3KtMsBF7Y1ZajS2xDKQdGOnEkAv/EgJAGBVP1ACxk6oxlQ9pQRwnm1JPpHk8iTblQNW9aASsMKXlYCLOK4EMHpjmGXxPqcRgBb8XAkYO6EaU/SqEsC73Lji7z+jHPAuu5IsKQMrLKWZvQi12QdpGN5SAnruaiUAoAWvKQFjJ1Rjil5XAjjPtiTXrPjnq5QE3sVSf6zmTiVgFW0/nWt2yTBYHnC8liu21ebM1/c7lUCHzOwfr58qAWP3XiVgYs4meU4Z4Dw3rvJne5IcURp4h32MuFi/2BGbrXO+15Lc0eLrm13C3JnYt6QLr4zkfVznVAIjdzKWIuzCYSVg7IRq1Pa3Hbf/mlMA57lwltrcpyJUg7mDSsAlfC5CNc7X9rJ/NyV5VJl7r8Z14fUktyj1qP24xdf+mPICI72+zT2U5JhSA4tm+Udq+8eO2/9LpwDOc+NF/vzyS/x/MDWWfuRS7lACLtD2sn+fVmJmtirB6J1u8bWXlBcY6fVtzux+oBVCNabmBSWAd1xsltrcrysR5GElYA3MZmSltmcobVHiwaixX8wOZR611/UfwPVtw25SZqANQjVqe6nDtl9VfjhPaSbaJ5QI8kUlYA32KgGVmUE7DDX2cTFgOG7/0PLr21cN6MqxCm2Y3Q+0QqjGlCwrAbyjNEtt7lalYsIOxIwQ1mbLrL/AXNszlP6VEg/CaxXauFmZR63tma/XKjEw8nv0XcoALJpQjSn5nhLAO25c8L8HY/QFJWAd7lcCVni+5de3l98wvFKhDfuqjd9yi699m/ICHTpZoY1PKjOwaEI1unC6gzbPKju8Y62z1JLkytm/D1OzN8mSMrAOW2IZSM6psU+I/tZ/Jyq1YznQcfuzlr+7dikx0JGXK7SxR5mBRROq0YX/0UGbrys7vGO9s88+rmRM0N1KwAY8qATMHKvQhhkmw7BcoY1/q8yj9lrLr28WB9CV71doYynJDqUGFkmoRhd+2kGbf63skGR9s9TmrlU2JmZHLKfFxn+071IGZpZbfn1LQA7Df6zQhu+scWt7GVGzOICuHK7Uzu1KDSySUI0u/H0Hbf6VskOSje2RdnmS7UrHhNyjBGyCZdiYO1KhjYeVufe+X6mdg0o9Wm0vI7oUsziA7pxxfw4MjVCNLvysgzZfUnbY0Cy1uc8oHxOyUwnQf1iAP6/QxheVufdqPYVvj71xO9ny65vFAYz9e/KAUgOL8l4loAMvJfl8xfbeVHJIsrFZanNXKR8TUfNJ/+NJnlfyaq5NveXyDibZr+STd6xCG1vSDBI9qty9djLtL9GoL4zbsy33oX2+t4COfD91ZpLd7zsSWBShGlPwMyWATc1Sm9uTOktZQZdqLg1yi3JXd0fFfmRwkiQ5WqHfGSTqv++kzr5n+sJ4PZ/k3pbbEMoCXTic5IkK7Xj4BFgYyz/SlVMV2/qpckN2LeA1PqWMjFzNJUGOKncnDlVsy15XJMnTFdrYor/1Xq0BPH1hvE6k/X2H7ldmoCO1fhu5zgELIVSjKzWDrv+p3Ezc9iRXLuB1Ls/mlpCEvqv5I+tbyt2JJyu2Za8rkubp6zMV2rlXqXtvuVI7+sK4rydtms/iAKjt6UrtePgEWAihGl35bxXb+lvlZuJ2LPC1fl05Gam9sx9ZNZxM88Q59Z1Is5ddrR/tBidJ2h8In3tGqXvtmxXb0hfGqcb3l1kcwJjvlZLm4ZMdSg5shlCNrrxQsa1/VG4mbHcWM0tt7hNKykg9WLGtx5W7U09UbOsLyk3qzZDcGUFun9Xcw2Vn6u4RSh3H0v7MV7M4gK7UXB7/EeUGNkOoRpfOKgG07rMtvOatysrI7E2yVKmtM6n7JCbvdjj1lmFbmvUvpu1EmhmqNXw1nr7us5oDhgeVe7TfYW0ziwPown+o2NZW35PAZgjV6NLrldp5SamZqLvS7IO2aPZVY2zurNjWQ8rdCzWXYbtbuUndGapPKndv/YfK7b2h5KNT6/P9B0oNVHYs9R58S5oZ3R5+AzZEqEaXlpUAWrMtyQ0tvfaVs9eHMdiRZpmsWh5V8l54NO0voTW3NZ74p5ldUqvPbUnyspL30rHKv4GW9IXROVGpDy3FLA6gvq9Vbs91DtgQoRpd+p4SQGvaDgmuU2JG4nMV2zqk3L1ScxnOe5Sb1J2pujXJM0reSw9Ubs8SV+NTa9DZLA6gtkOp9xBS0jyI9JayA+slVKNrbyoBLNytSa5quY1PKDMjcUfFtvYrd6/UPB87lZvUnSE573fClP45XLkfJE04oi+MR81B5yeU+53P0NvKAFXUXi5/SyyXDKyTUI2u/VAJYOFuqdTObqVm4GoOMB5X7l46OtL+Rn8dqNzeviRHlH3y/WDeF1yHxqPmoPPUZ3E847MDVdV+CClplrw1Yw1YM6EaXftLJYCF+lKSyyu19VnlZuD2VWzL0o/99K2R9jf661Dq7yt8R+yrpR+cuw5ZFnQcau7ROtXl0fbN3rfZ5lDfQx20aSlIYM2EanTtBSWAhbk1yTUV27s8yXZlZ6BqzhJYTnJMyXvpROoObB9QcpL8fgdtbo1grW8e6KjdnfrCaNR8YGdqg80vp5mdtkU3g048mm4ePplf6+wnCVySUI0+eFUJYCFu6aDNHcrOQN1fsa2vKXevPTDSfkd/HUs3S8JuTbMnkFmT/XA43S0NvDUGDcdgf+oukTaFYO3h2XVyq+4Fnfv9jtrdkmY/Scu+AhclVKMPXlcC2LQHUm/Zx5WuTHKj8jMwe1PvyeMzsfRj3x1OvUHJLTGITeOW1N8vZO5gLAHYp37QlfmgoT33zrdrYMf7UAf95u0RfpfNl3q810cAeuNYut2Xel+SN+JBYmAVQjX64DklgE3ZneSqDtvf5hQwMA9WbOsbyj0ID420/9FvXS4HujPNAPKUlyTtSyjwlY7bv2PifWFvmqD5jTRh0VMZ1mzOrpZIG8ssjr2zc2+pR+inLh9CSpKlJM9mug+g7JjdHxyZ3Su8HQ/jQBKhGv3xYouvbcCfMduW5LaOj+EanzMGZNfsx1Et9yn5IDxa+ce52WokzSzWLp/A3pLkq2kGlKfQJ/elGQiahydP9Oj6c7LjY5hKX9iVZnDwmZwbHHxi1jdW3hv8+sDe1+c7/Ey9leHN7kvOhWlPVL4vBNavDw993DH7zhj7kpB70yyD+/Ls/T47uz+4I+cePPg1XRKEavTHX7b42h9UXkbsd3pyHJaAZChqPn1+VLkHpeYynXcqNzNdP4GdNAPKT2RcgcqunAtP3s65gbA7cv4Ael/e7/U9OY55XxjDzLUdeXeQ+lSawcGdufSspI8M7L2eSPJIR21vmdV1KDMXDkSYBkO8Rz/ek2PZl/GEa6vNQnsizTK4l9pX0p6TEKEa/fFCkjdbeu1fUF5G6kvpZh+11ZitxlB+OOys2N63lHxQ9ldsa2fsz8A5t/fkOJZyLlB5eED125VzAdpq4cmlfGii16CS+cy1+TJPuwbw/T4fGFz5dP1qQepar9FDc1+6WQZyrs+zOHbN+sbbs369FGBo+vAQ0krzcO3lDOOBpJXfk2/k4rPQ1vN6MGnvVQJ65M/TzjJ2v6i0jNCeNEFWn9yY5CWnhh6rOXB9Ms2T4wzL8dQbTP2cPsLMiTSBSl8Go7ekeUr53jSD9EfSj6VsdyT5aJJfTXJdkk9n83sg3ZS6y79eyqEk/yrN4Faf3LHimI4m+dPUndnbdh8Yk8+nGSTt0r7Z/44meTrJ4Y6OY9fs+/w3I0SDMf2We7Znx7Q1zQNJT8x+/32n4/uKWt+TH/U7hqm77O2331YF+uQPW3jN00keVFpGZHuaUK2P/iCCNfqr5k3PneluIImN25u6+yxd1vH73ZF2Bydu9oN7XQ6m7hK163UmyQ+SPJ/klZbO7Y4k70tydZKr0izD12Zwspzkwz2r88sZztJKx2d94SdJfrTJPjF/6v2X08wgfH+aAcEPdFSP3UmODfA68nCaQLxP143Ds77Sdj33pQmmb8sww9bjaWbjTPl++ivpz4MOat5P+zKcpRfn35F/keRvFnTftPI+KWkeDkrqz7A+lH7NsIfqzFSjb15McsOCX/MqZWVkfqvHx2a2Gn1Vcymz5QjUhupwmgdxliq1d9APUlbYn2Zvrb4GKlvSDNpcOHAz3+fk+RV/9laakGWl6y745/lA0Ac6fM9LPazz9bP6DSEUWK0/rHQyyc9X+fOPpf+zh64e6HXkvjQPNGzt0XVjPntt3ieezeaC2AtnYuwMMBWHkvx6+v0QUuk7cv6QUkmX90clH9EVmTqhGn3zF1l8qJY0ez0Z6GcMHkl/9lFbzTU+b/TUFyu29U3lHrSvpd4TsHsjVON812dYM5WScwNGQx3Y3pH+zai8IsMJ1i5l64CP/dqBX0feSD+Dy62X6BfHL/LnQwhhgXr2pwl1hnrfsSXDfxjAwwxM3nuUgJ55KcmpFl73fUrLCDyQ5Eo3WLBuB1J3YNKyNcN2KPU2Qt8y65+w0vVpZnNQx0d7elxXVLwW8W6/NvDj//AA+8/Oi/xvSXcELnCLeyWgS0I1+uiFFl7zamVl4O7KYpcyPZvkyZaO9ao0+75BX3yhYluHlHsUai7feb9yswrBWj2/2uNjE6x1Z+sI3oOZ0IB7JdqyVwmYMqEaffRSkjcX/JpCNYbsrix2WdSzSe5O8r20MzM0ObfZPPThZn+pYnsGsMah5nnc4kcpF2GwqI7ren58gjU26nCSO5UBcK9ECz6kBEyZUI2++t6CX+9yJWWgtqedQG3uhZaO+8oku50+euDBim0dV+5ROTrSfsqwXO/a0rpPD+AYBWvdGMMDD4I1YAr3SkeVobqblIApE6rRVy9k8TNoblVWBmZ7kj0LfL0LA7WkvX0Mk+SzTiEd25G6s9Qs/Tgu36rY1lKSXUrORdzi+tKqLQM5ziviafzaxvIUvmANGLs97pWq+7QSMGVCNfps0TNorlNSBmTRgdrpvDtQa+uzNnd5LIVHt+6p2NZykmNKPionZue1ln1KziXsj0HxNg1l2WpP49c1pqfwBWuAeyUWaYsSMGVCNfps0TNorlJSBqKNQO3BwmftxZbeyyeSbHNK6cjOim09oNyj9MBI+yvDdDjJZakb9k7FkB6+25PkK05ZFR8b6TXEUqLrdyYeFgT3SlxohxIwVUI1+u6xBb+eJSAZgpqB2ty3W3w/u5xSOnCwYltnZj/gGOcP8zMj7bcM14djiaNFG9rDd48muTkGDdu2NNL3dUXs1bgeR2c1c92FYd0rmdndPiuCMVlCNYbguQW+1o3KSc89vsDXejVrC9Tmnm7pPV2ZZLdTS2U1l9L7hnKP2kMj7bcM2/7Zd6sZJ4tx/QCP+USaQcNHnL5WjfUp/Fv0naLl2XV2j1LAIO1xr9S6a5WAqRKqMQRHkry5oNe6Mpaio59uTBOoXb6g13sx65/x8FSSsy29v9ucYio6ULm9+5R81B6t3N7DSs4aHUsze8LA+OZtHfCx35dm1tpJp7EVHx3xe7svBpxXcybNEqsfjv1yYSz3SmaatuNTSsBUCdUYiu8t8LVMT6Zvtif53SwuUHs6G1/O8bstvk97TlHL/RXb8gNtGmqe5y8qN+t0X5r9QyznNl0n0sy22x8BCetzLML5C7/vr0j9B2qAdu2PB1DasKQETJVQjaF4IcmpBb3WJ5STHtmexS4pciTNjLONem6Bn7ULXRXLQNK+fUm2VGzvSSWfzA/xWrak/mxLxuGWGDCaunkg8JUI1zbjaJI704TVU3l4ZuozHo/Pzvd+3R9Ga/4Ayp2xJ+lmnJl9N+6eXTdhkoRqDMljWdzSdHcpJz2wyEDtbJLfy2L2IHysxfdsGUja9uWKbZ2c/ThjGmrOAvqCcrNBKweMzFy7tDEPCj0a4dp6LF/QF/YkOTzx68fyRN7zodk5v8XHACbjcJrlXYVr6/uefCTNwxdXpHkA4ZiyMGVCNYbmOwt6nRuUko7tyeICtdNJ7l7w8T3d4nu3vAxt2Zu6S1A8ruST8kTFtpZm/Rk26nDOzVw7qhzvOJlpDQo9uuJ9Ljv95zk+q8tlaQZXDRCef/0Y+4DzPEwzMw1c6zyI9G5nZvePK78n74sHSuEdQjWG5oUkry7otcxWoyt3pZmltggvJnmwhWN8KsmbLb3/K33+aMndFdtazjSfYp/6D+/lkfZnxutEmod4Lksza2l5Yu9/Oc3g+Xwpv+szzUGhQ2kGxKYcss4D1flstFtiX9S1fO+NKVxbzrkBYmEasPJad0vOLfk71RneJ2f3ivMHj/b4noSLu+ztt99WBYbokTQD85v1e0pJZV9Kcs2CXuvJJN9r+Xj/sMXXPpLFLFcJczX3oXo9nmifoh1JrqvY3qMD/9w8qsv01sNJvpi6e1DWcDLJy0m+Hw8+lOxNsyz3HSN9fyeTPJvkz31fL/Q78PZZ3xnKtePM7FrwZBYTpj/T4rG+kib077s2a/CEa7ea98SuJDsHdr3zPQkVCdUYskUM9r+a5KBSUskDSa5awOucTfLHSV6qcMy7094+aGdjJgYAdO1Akt9OsnVgx72c5M+SvJZmMNqSRBu3K83g4W+m7jLKi3ImyQ+SPK8vVO8zfRxwXk7z8J6BYmARdiS5Kc0Mrq0DfQ/umWDBhGoM2fYsZk+qP0idcILp2pbkd5JcvoDXOpXkscrHv6gwcDWn087ylQDA+u1KcnWawaNPpx+D5fPA5JUkP0nyoxgMatveJB9PMzN3Z8+O7XiSH8/uIQ0M9sN8FvdNHfWX5TSDxX8aS5UBde6VPtnT70jfk1CJUI2huyvJDZt8DYP6tOnWNMukLMJzaZ667MLjWUwouBozRgGgv+YD5u+f/fUDWeyT2vPQLGlmGiXNIFBiIKhPdqUJXK9K8pEkH0s7s9qWk/wwyc/TPFH/VgSpQ7Q3yYfSBG2LumbMrxXzvmEpbqCv35FtPph04bXQ9yR0QKjGGCxiFk2NvamYnkWEvknd5R4vZlEzQy/m6SRP6TIAMCg7Vvmzj6bZ4D45N9BzIQM/4+4Hv5wmUFnNan1Cf5hmX1l5rbjQ60n+Qf8ARnbdW8/ezD9N8je+K6GfhGqMxSJm0fyeMrJAi1oysYvlHi9mUSHhxRxJMxsPAAAAAKB3hGqMyWaDNctAsgjbk/xWFrNUYh9nULa5v1oi3AYAAAAAekqoxthsNljrcs8qhm9RM7n6HvC2ub/a2SR360oAAAAAQN+8RwkYme9u8r/fPvsfrNcDWUyg9lz6P2Pyj1t87cvThHYAAAAAAL1iphpjtD3Jnk3892bKsB63Jrl9Aa/zZpJjSV6ayOfM5xAAAAAAGBShGmO12QH/N5Pcq4wUfCnJNQt4naEuO7on7c7stM8hAAAAANAbQjXGbLPBmgF9LubWJLdk8/uKnU5yPMOZnbaa/Uk+0eLrm7EGAAAAAPSCUI2x22yw9mqSg8rICouanfZ0kqdGUpMHklzV4usL1gAAAACAzgnVmIJtSX4nG59V9GKSbyvj5O1O8tlsfnbaqSSPjbA+NYK1P86wZ/UBAAAAAAMmVGNKHo9gjfXblmRnNh8YvZnkRJr908aq7WAtafaee063BAAAAABqE6oxNZsZ9BesTc+eNEuIbtaYlnps8zPmswgAAAAA9JZQjSnan+QTG/xvDeZPw61JbomlHjeqRrA21doCAAAAAB0RqjFVu5PctsH/9nSSB5VwlBa11OPpJMcz7f2/agRrZ5N8J8kLui4AAAAA0DahGlO2LcnvZGOzkd5Mcq8SjsqXklyzydc4m+S7sefXImu6Fs+l2WsNAAAAAKA1QjXY+MC/WTLjcFeSGzb5GmeT/Emms29a7fquxZtJjmXaswMBAAAAgBYJ1aBxa5LbN/jfPh1hyhDtTvLZbG7fNGHa2mt9W6W2Xk1yUMkBAAAAgEUTqsH5NroPlH3WhkOY1o3tSX5rk3V3fgAAAACAzgjV4N02GrqcTfJMku8p4ajO64Xn+E8irNmMR5JcWakte9ydsyfJh9Isj2nJWgAAAADYAKEaXNz+JJ/YwH93KsljytcbdyW5NpsL095MciLCma4/W5s5f3+e6YWhe5L8RpoQ87kkR3Q9AAAAANg4oRpc2o1p9lvbyMwae611664kN2zyNU4l+U8RprVhM/sYbtTZJK8l+faIr1e/luRjK65ZQn4AAAAAWBChGqzNRveDMsOprhuTbEtyzSZf58Ukf5FmqTzatdF9DDfrdJJXMvzlWm9N8vFV+rxrDwAAAAAsmFAN1mej+3KdTnI8Qpo2z8sns7m9uqa6RGBfzt9tHbb/apLl9D9g25bkg0mWklx9keuQff8AAAAAoCVCNdiYjYZrp5K8EOHaIsyXutvsEo+vJvkvs/NCt7qatbbSm0n+c5L/nm5neW1L8r4k/yzJh7K22ZcvZrxLWwIAAABA54RqsDmbmbn2/ViabSP2JPmNbH5W2gsZ/tJ/Y3Rrkls28Jlqy9kkP0ny4yT/K8nPsrhQfNvsrx9M8gtJPjL7+/X2bWEaAAAAAFQgVIPF2J7kM1n/LBvhztrcmuS6bG4W03wG0hHlHIS7svlZiDWcuuCff5bk71b8868k+d9X/PNGQrOLEaYBAAAAQEVCNVisbUk+nuTarH+mjWUIzydII0n2J/mEMrzjbJI/06cBAAAAoD6hGrRne5J/mbXthbTS2SSvJfnLTC9g25Nmn7TNBGmnZ7UTOozHtjR76F0z4RqY1QoAAAAAHROqQR0bnXU1D9j+a8a5/9qtSZaSXJ3N7aH1apLXY4+6KRjKspCLYgYrAAAAAPSEUA3q254mRNrIknank/w/Sf42wxtk35ZmP6mlJL+aze0rdSrJj5P8VZKXdKlJ2pPkU9lcGNtXp5O8ErPSAAAAAKBXhGrQrRuT/ItsfMnD00n+W5L/N8nP0p+AaR6g/R+zv25m2b6zaWah/XWEaKz+Gfr1DH/fNfv/AQAAAEDPCdWgX25M8ktJPpKNB1Fnk/wkTcj2d2lmtf1jFhtGbZv99X1Jrkjyi2nCs1/N5mYOzY/9xxnmbDy6tZlZoF04leQvYkYaAAAAAAyCUA36b3uSf5bkQ9ncjK+V5uHVWn0wm1uu8WLtz4M/M9BYtPks0N9YcN/djPmypQJjAAAAABggoRoM03x5xfenCdv+aTa2fGSbTs3++tMk/zPtzJiDtVo5C3SzMypL5qHxT5P8ffq1NCsAAAAAsEFCNRif+dKM/yRNiJAk/1ua8G01F85CK81im88um3sryT/M/l5wwNA+K/PPyWqfkQvDtzdn/X+lH8/+KjQGAAAAgJETqgEAAAAAAEDBe5QAAAAAAAAALk2oBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAAAAAECBUA0AAAAAAAAKhGoAAAAAAABQIFQDAAAAAACAAqEaAAAAAAAAFAjVAAAAAAAAoECoBgAAAAAAAAVCNQAAAAAAACgQqgEAAADw/7dnBwIAAAAAgvytR1igNAIAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgCHVAAAAAAAAYEg1AAAAAAAAGFINAAAAAAAAhlQDAAAAAACAIdUAAAAAAABgSDUAAAAAAAAYUg0AAAAAAACGVAMAAAAAAIAh1QAAAAAAAGBINQAAAAAAABhSDQAAAAAAAIZUAwAAAAAAgBEyZY5aTlTWlgAAAABJRU5ErkJggg==';

  // ── CSS ───────────────────────────────────────────────────────────
  const CSS = `
    @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&display=swap');

    #arceane-header * { box-sizing: border-box; margin: 0; padding: 0; }

    #arceane-header {
      position: sticky;
      top: 0;
      z-index: 9000;
      background: rgba(8,8,8,0.96);
      backdrop-filter: blur(14px);
      border-bottom: 1px solid #1e1e1e;
      font-family: 'Raleway', sans-serif;
      -webkit-font-smoothing: antialiased;
    }

    #arceane-header .ah-bar {
      display: flex;
      align-items: center;
      padding: 0 32px;
      height: 52px;
      gap: 0;
    }

    /* Logo */
    #arceane-header .ah-logo-wrap {
      display: flex;
      align-items: center;
      gap: 14px;
      text-decoration: none;
      flex-shrink: 0;
    }
    #arceane-header .ah-logo {
      height: 28px;
      width: auto;
      display: block;
    }
    #arceane-header .ah-sep {
      width: 1px;
      height: 20px;
      background: #282828;
      flex-shrink: 0;
    }

    /* Nav pills */
    #arceane-header .ah-nav {
      display: flex;
      align-items: center;
      gap: 2px;
      padding: 0 16px;
      flex: 1;
      overflow: hidden;
    }

    #arceane-header .ah-nav-item {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      font-size: 10px;
      font-weight: 600;
      letter-spacing: 0.8px;
      text-transform: uppercase;
      text-decoration: none;
      color: #585450;
      padding: 5px 10px;
      border-radius: 3px;
      white-space: nowrap;
      transition: color 0.14s, background 0.14s;
      border: 1px solid transparent;
    }
    #arceane-header .ah-nav-item:hover {
      color: #e8e4dc;
      background: rgba(255,255,255,0.05);
    }
    #arceane-header .ah-nav-item.ah-active {
      color: #e8e4dc;
      background: rgba(255,255,255,0.06);
      border-color: #282828;
    }
    #arceane-header .ah-nav-icon {
      font-size: 12px;
      line-height: 1;
    }

    /* Overflow dropdown */
    #arceane-header .ah-more-wrap {
      position: relative;
      flex-shrink: 0;
    }
    #arceane-header .ah-more-btn {
      display: inline-flex;
      align-items: center;
      gap: 5px;
      font-size: 10px;
      font-weight: 600;
      letter-spacing: 0.8px;
      text-transform: uppercase;
      color: #585450;
      background: none;
      border: 1px solid transparent;
      padding: 5px 10px;
      border-radius: 3px;
      cursor: pointer;
      font-family: 'Raleway', sans-serif;
      transition: color 0.14s, background 0.14s;
    }
    #arceane-header .ah-more-btn:hover {
      color: #e8e4dc;
      background: rgba(255,255,255,0.05);
    }
    #arceane-header .ah-more-btn svg {
      width: 10px; height: 10px;
      transition: transform 0.15s;
    }
    #arceane-header .ah-more-btn.open svg {
      transform: rotate(180deg);
    }
    #arceane-header .ah-dropdown {
      display: none;
      position: absolute;
      top: calc(100% + 6px);
      right: 0;
      background: #111;
      border: 1px solid #222;
      border-radius: 3px;
      min-width: 200px;
      padding: 4px;
      box-shadow: 0 8px 32px rgba(0,0,0,0.6);
      z-index: 9100;
    }
    #arceane-header .ah-dropdown.open { display: block; }
    #arceane-header .ah-dropdown-item {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 11px;
      font-weight: 500;
      letter-spacing: 0.5px;
      text-decoration: none;
      color: #a09c96;
      padding: 8px 10px;
      border-radius: 2px;
      transition: color 0.12s, background 0.12s;
    }
    #arceane-header .ah-dropdown-item:hover {
      color: #e8e4dc;
      background: rgba(255,255,255,0.06);
    }
    #arceane-header .ah-dropdown-item.ah-active {
      color: #e8e4dc;
    }

    /* Right side */
    #arceane-header .ah-right {
      display: flex;
      align-items: center;
      gap: 10px;
      flex-shrink: 0;
      margin-left: auto;
    }

    #arceane-header .ah-back-btn {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      font-size: 9px;
      font-weight: 700;
      letter-spacing: 2px;
      text-transform: uppercase;
      text-decoration: none;
      color: #e03a32;
      background: rgba(224,58,50,0.08);
      border: 1px solid rgba(224,58,50,0.2);
      padding: 6px 12px;
      border-radius: 2px;
      transition: all 0.14s;
      white-space: nowrap;
    }
    #arceane-header .ah-back-btn:hover {
      background: rgba(224,58,50,0.16);
      border-color: rgba(224,58,50,0.4);
    }
    #arceane-header .ah-back-btn svg {
      width: 9px; height: 9px;
    }

    /* Loading / error state */
    #arceane-header .ah-loading {
      font-size: 9px;
      font-weight: 500;
      letter-spacing: 1.5px;
      text-transform: uppercase;
      color: #383430;
      padding: 0 16px;
    }

    /* Responsive */
    @media (max-width: 600px) {
      #arceane-header .ah-bar { padding: 0 16px; }
      #arceane-header .ah-nav { display: none; }
    }
  `;

  // ── Helpers ───────────────────────────────────────────────────────
  function currentPage() {
    return window.location.pathname.split('/').pop() || 'index.html';
  }

  function isActive(url) {
    const current = currentPage();
    const target  = url.split('/').pop().split('?')[0];
    return current === target;
  }

  // ── Parse index.html to extract tool list ─────────────────────────
  function parseTools(html) {
    const parser = new DOMParser();
    const doc    = parser.parseFromString(html, 'text/html');
    const cards  = doc.querySelectorAll('.card');
    const tools  = [];

    cards.forEach(card => {
      const nameEl = card.querySelector('.card-name');
      const btnEl  = card.querySelector('.card-btn');
      const iconEl = card.querySelector('.card-icon');
      if (!nameEl || !btnEl) return;

      const href = btnEl.getAttribute('href');
      if (!href || href === '#') return;

      // Resolve relative URLs against the index base
      const base  = INDEX_URL.replace(/\/[^/]*$/, '/');
      const absUrl = href.startsWith('http') ? href : base + href;

      tools.push({
        name: nameEl.textContent.trim(),
        icon: iconEl ? iconEl.textContent.trim() : '🔧',
        url:  absUrl
      });
    });

    return tools;
  }

  // ── Build header DOM ──────────────────────────────────────────────
  function buildHeader(tools) {
    const MAX_VISIBLE = computeMaxVisible();

    const visible  = tools.slice(0, MAX_VISIBLE);
    const overflow = tools.slice(MAX_VISIBLE);

    // Nav items
    const navItems = visible.map(t => `
      <a class="ah-nav-item${isActive(t.url) ? ' ah-active' : ''}"
         href="${escAttr(t.url)}" title="${escAttr(t.name)}">
        <span class="ah-nav-icon">${escHtml(t.icon)}</span>
        ${escHtml(t.name)}
      </a>
    `).join('');

    // More dropdown
    const moreHtml = overflow.length > 0 ? `
      <div class="ah-more-wrap" id="ah-more-wrap">
        <button class="ah-more-btn" id="ah-more-btn" onclick="window.__ahToggleMore()">
          +${overflow.length}
          <svg viewBox="0 0 10 6" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M1 1l4 4 4-4" stroke-linecap="round"/>
          </svg>
        </button>
        <div class="ah-dropdown" id="ah-dropdown">
          ${overflow.map(t => `
            <a class="ah-dropdown-item${isActive(t.url) ? ' ah-active' : ''}"
               href="${escAttr(t.url)}">
              <span>${escHtml(t.icon)}</span>
              ${escHtml(t.name)}
            </a>
          `).join('')}
        </div>
      </div>
    ` : '';

    return `
      <div class="ah-bar">
        <a class="ah-logo-wrap" href="${escAttr(MENU_URL)}" title="Arcéane Tools — Menu">
          <img class="ah-logo" src="data:image/png;base64,${LOGO_B64}" alt="Arcéane">
        </a>
        <div class="ah-sep" style="margin: 0 14px;"></div>
        <nav class="ah-nav" id="ah-nav">
          ${tools.length > 0 ? navItems : '<span class="ah-loading">Chargement…</span>'}
        </nav>
        ${moreHtml}
        <div class="ah-right">
          <a class="ah-back-btn" href="${escAttr(MENU_URL)}">
            <svg viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M6 1H2a1 1 0 00-1 1v6a1 1 0 001 1h6a1 1 0 001-1V6M8 1L4.5 4.5M6.5 1H8.5V3" stroke-linecap="round"/>
            </svg>
            Menu
          </a>
        </div>
      </div>
    `;
  }

  function computeMaxVisible() {
    const w = window.innerWidth;
    if (w < 800)  return 0;
    if (w < 1000) return 2;
    if (w < 1200) return 3;
    if (w < 1400) return 4;
    return 5;
  }

  function escHtml(s) {
    return String(s)
      .replace(/&/g,'&amp;').replace(/</g,'&lt;')
      .replace(/>/g,'&gt;');
  }
  function escAttr(s) {
    return String(s).replace(/"/g,'&quot;');
  }

  // ── Dropdown toggle ───────────────────────────────────────────────
  window.__ahToggleMore = function() {
    const btn = document.getElementById('ah-more-btn');
    const dd  = document.getElementById('ah-dropdown');
    if (!btn || !dd) return;
    const open = dd.classList.toggle('open');
    btn.classList.toggle('open', open);
  };

  document.addEventListener('click', function(e) {
    const wrap = document.getElementById('ah-more-wrap');
    if (wrap && !wrap.contains(e.target)) {
      const dd  = document.getElementById('ah-dropdown');
      const btn = document.getElementById('ah-more-btn');
      if (dd)  dd.classList.remove('open');
      if (btn) btn.classList.remove('open');
    }
  });

  // ── Mount ─────────────────────────────────────────────────────────
  function mount() {
    // Inject styles
    const style = document.createElement('style');
    style.textContent = CSS;
    document.head.appendChild(style);

    // Create header container
    const header = document.createElement('div');
    header.id = 'arceane-header';
    header.innerHTML = buildHeader([]); // skeleton first

    // Prepend to body (before any existing content)
    document.body.insertBefore(header, document.body.firstChild);

    // Add top margin to first element after header if needed
    const firstContent = header.nextElementSibling;
    if (firstContent && getComputedStyle(firstContent).position !== 'sticky') {
      // no margin needed — header is sticky, it doesn't push content
    }

    // Fetch index and populate nav
    fetch(INDEX_URL, { cache: 'no-cache' })
      .then(r => r.ok ? r.text() : Promise.reject(r.status))
      .then(html => {
        const tools = parseTools(html);
        header.innerHTML = buildHeader(tools);
      })
      .catch(() => {
        // Silently fail — header stays with just the logo + back button
        header.innerHTML = buildHeader([]);
      });
  }

  // Run when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

})();
